### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TechPro424** [spotistatsapp/spotify.js#14]
A documentation for the package would be very beneficial, as we can refer to it for the various methods in the package.

**Comment by stingalleman** [comment]
We use JSdoc, so having auto-generating documentation like TypeDoc should do the job. I'll look into this if I have time!

**Comment by TechPro424** [comment]
Thanks! :)

**Comment by TechPro424** [comment]
When would the documentation be available? (an approx date)
